spring.application.name=Hospital-Management-System

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDB
spring.datasource.username=postgres
spring.datasource.password= root@123
# spring.jpa.hibernate.ddl-auto= create-drop  when we run our springboot application it create the db and all the tables in it and once we close the application it will drop all the tables and db....

# they both are used in production environment.....
# spring.jpa.hibernate.ddl-auto = validate  it validates the schema, makes sure the tables are present in the db and they have same structure if not it will throw an error
# spring.jpa.hibernate.ddl-auto = none  it will do nothing it will neither create nor validate the schema
spring.jpa.hibernate.ddl-auto = create

# it will show the sql queries in the console
spring.jpa.show-sql=true    
# it will format the sql queries in a proper way
# spring.jpa.properties.hibernate.format_sql=true 

server.servlet.context-path=/hps/v1

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# security configuration
# now this will be the default username and password for our application when we run it, we can change it as per our requirement
spring.security.user.name=kavya
spring.security.user.password=kavya101
